version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"
    target-branch: "main"
    groups:
      api3:
        patterns:
          - "@api3/*"
          - "@nodary/*"
      others:
        patterns:
          - "*"
    ignore:
      - dependency-name: "@types/*"
      - dependency-name: "babel/*"
      - dependency-name: "changeset/*"
