version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:30"
    target-branch: "main"
  - ignore:
      - dependency-name: "^((?!@api3\/|@nodary).)*$"
    groups:
      api3:
        patterns:
          - "@api3/*"
          - "@nodary/*"
      others:
        patterns:
          - "*"
