version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:48"
    target-branch: "main"
    allow:
      - dependency-name: "@api3/*"
        dependency-type: "all"
        update-type: "all"
      - dependency-name: "@nodary/*"
        dependency-type: "all"
        update-type: "all"
    groups:
      api3:
        patterns:
          - "@api3/*"
          - "@nodary/*"
      others:
        patterns:
          - "*"
