# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Package

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  pack-local-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'yarn'
      - name: Install Packages
        run: yarn install
      - name: Pack Package
        run: yarn package
  require-user:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'yarn'
      - name: Install Packages
        run: yarn install
        if: github.actor == 'renovate[bot]'
      - name: Pack Package
        run: yarn package
  required-checks-passed:
    name: All required checks passed
    runs-on: ubuntu-latest
    needs: [pack-local-package, require-user]
    steps:
      - run: exit 0