# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to Github Pages

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  pack-local-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'yarn'
      - name: Install Packages
        run: yarn install
      - name: Pack Package
        run: yarn package
      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: logos.tgz
          path: ./logos.tgz