name: Trigger on Registry Package Publish

on:
  registry_package:
    types: [published]
  push:
    branches: [ main ]
permissions: write-all
jobs:
  Trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Call logos workflow
      run: |
        curl -d "{\"event_type\": \"registry_package\"}" -H "Content-Type: application/json" -H "Authorization: token ${{ secrets.PAT }}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/api3dao/logos/dispatches"