name: Trigger on Registry Package Publish

on:
  registry_package:
    types: [published]
  push:
    branches: [ main ]
permissions: write-all
jobs:
  Trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Call logos workflow
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: api3dao,
            repo: logos,
            workflow_id: 'release.yml',
            ref: 'main',
          })