name: Trigger on Registry Package Publish

on:
  release:
    types: [published]
jobs:
  Trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Repository Dispatch - Release logos
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.PAT }}
        repository: api3dao/logos
        event-type: release
