name: Trigger on Registry Package Publish

on:
  registry_package:
    types: [published]
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.2.4
        with:
          configurationFile: example/renovate-config.js
          token: ${{ secrets.GITHUB_TOKEN }}