name: Trigger on Registry Package Publish

on:
  registry_package:
    types: [published]
  push:
    branches: [ develop ]
permissions: write-all
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Open PR
        id: open_pr
        uses: wandpsilva/open-simple-pr@v1
        with:
          branch-origin: 'develop'
          target-branch: 'main'
          title: 'my pull request'
          body: 'body of my pull request' 