name: Trigger on Registry Package Publish

on:
  registry_package:
    types: [published]
  push:
    branches: [ main ]
  schedule:
    - cron: '0/5 * * * *'
  workflow_dispatch:
permissions: write-all
jobs:
  build:
    name: Create Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.2.4
        env:
          # Repository taken from variable to keep configuration file generic
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          # Onboarding not needed for self hosted
          RENOVATE_ONBOARDING: "false"
          RENOVATE_PLATFORM_COMMIT: "true"
          # Override schedule if set
          RENOVATE_FORCE: ${{ github.event.inputs.overrideSchedule == 'true' && '{''schedule'':null}' || '' }}
        with:
          configurationFile: renovate-config.json
          token: ${{ secrets.RENOVATE_TOKEN }}