name: Trigger on Registry Package Publish

on:
  registry_package:
    types: [published]
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Open PR
        id: open_pr
        uses: rematocorp/open-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          from-branch: update-packages
          to-branch: main
          repository-owner: hiletmis
          repository: react-icons-api3
          
      - name: Echo mergeable PR number
        run: echo ${{ steps.open_pr.outputs.pull_number }}