name: Trigger on Registry Package Publish

on:
  registry_package:
    types: [published]
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  Trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: hiletmis/react-icons-api3
        event-type: registry_package