# https://github.com/changesets/action
name: Release

on:
  push:
    branches:
      - production

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          
      - name: Install dependencies
        run: yarn --network-timeout 300000

      - name: Build package
        run: yarn build-svg

      - name: Check release
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
          commit: "ci: release packages"
          title: "ci: release packages"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Create Pull Request
        if: steps.changesets.outputs.published == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          branch: production
          base: main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}